# Generated by Django 3.2.7 on 2021-09-12 12:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamdash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file2',
            field=models.FileField(default='none', storage=django.core.files.storage.FileSystemStorage(location='/media/videos'), upload_to=''),
        ),
    ]
