# Generated by Django 3.2.7 on 2021-09-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamdash', '0002_video_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='filepath',
            field=models.FileField(default='none', upload_to=''),
        ),
    ]
